export const environment = {
    apiURL: 'https://emp-mgmt-dev.azurewebsites.net',
    token: 'eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJQcmluY2UiLCJJZCI6IjEiLCJVc2VySWQiOiIzIiwianRpIjoiMGJiODVhOWYtNzQ0My00MTQzLTk1MDEtY2EzMmNlY2Y5OTRmIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiU3VwZXJBZG1pbiIsImV4cCI6MTcyMzM1MzcyOSwiaXNzIjoiSnd0SXNzdWVyIiwiYXVkIjoiSnd0QXVkaWVuY2UifQ.GPuvzhVm0p_xpVbXZqajAMINkljlWxy-VPN76c_jH4U'
};
